### ISSUE TITLE
Can't find "is_employee" option

### ISSUE THREAD

**Issue by bilgehnbilge** [xHookman/IGexperiments#1]
First off all IGexperiments working good. I enable developer settings but all of them is just number. I can't find "is_employee" option

**Comment by xHookman** [comment]
Hey I'm sorry i'm stupid i forgot that experiments names has changed to unreadable name so this is normal :(

**Comment by Swakshan** [comment]
![Screenshot_2023-03-13-15-37-43-374_com instagram android](https://user-images.githubusercontent.com/56347042/224671134-c20ae7eb-ca09-4968-b26e-6aff5af8354a.jpg)
![Screenshot_2023-03-13-15-37-39-370_com instagram android](https://user-images.githubusercontent.com/56347042/224671148-78e9a472-fa9f-4d72-b230-102eb8c62374.jpg)

I believe it happens only with stable releases.
It's because in stable builds "id_name_mapping.json" isn't generated.
I'm using Alpha build and am not facing this issue

**Comment by Swakshan** [comment]
In case you want to find "is_employee" in the ocean of number, search "28538", this is the numberic value for it
